# Generated by Django 5.0.1 on 2026-04-19 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0004_enrollment_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.TextField(verbose_name='Ответ студента')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Ожидает проверки'), ('ai_checked', 'Проверено AI'), ('approved', 'Утверждено преподавателем')], db_index=True, default='pending', max_length=20, verbose_name='Статус')),
                ('final_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Итоговый балл')),
                ('teacher_comment', models.TextField(blank=True, default='', verbose_name='Комментарий преподавателя')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignment_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Ответ студента',
                'verbose_name_plural': 'Ответы студентов',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='AIEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Оценка AI (0–100)')),
                ('feedback', models.TextField(verbose_name='Текстовый фидбек от AI')),
                ('model_name', models.CharField(default='stub', max_length=100, verbose_name='Название модели LLM')),
                ('prompt_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Токенов в промпте')),
                ('completion_tokens', models.PositiveIntegerField(blank=True, null=True, verbose_name='Токенов в ответе')),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_evaluation', to='assignments.assignmentsubmission', verbose_name='Ответ студента')),
            ],
            options={
                'verbose_name': 'Оценка AI',
                'verbose_name_plural': 'Оценки AI',
            },
        ),
        migrations.CreateModel(
            name='OpenAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(help_text='Текст задания, который видит студент.', verbose_name='Условие задания')),
                ('reference_answer', models.TextField(help_text='Используется как контекст для LLM-грейдера. Студентам не показывается.', verbose_name='Эталонный ответ / критерии оценки')),
                ('max_score', models.PositiveSmallIntegerField(default=100, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(100)], verbose_name='Максимальный балл')),
                ('is_active', models.BooleanField(default=True, help_text='Неактивные задания не принимают новые ответы.', verbose_name='Активно')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_assignments', to=settings.AUTH_USER_MODEL, verbose_name='Автор задания')),
                ('lesson', models.ForeignKey(blank=True, help_text='Необязательная привязка к уроку курса.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='assignmentsubmission',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assignments.openassignment', verbose_name='Задание'),
        ),
        migrations.AlterUniqueTogether(
            name='assignmentsubmission',
            unique_together={('assignment', 'student')},
        ),
    ]
