# Generated by Django 5.0.1 on 2026-04-26 17:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0001_initial'),
        ('courses', '0007_add_assignment_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID попытки')),
                ('code_content', models.TextField(verbose_name='Код студента')),
                ('status', models.CharField(choices=[('pending', 'В обработке'), ('success', 'Выполнено успешно'), ('failed', 'Ошибка выполнения')], db_index=True, default='pending', max_length=10, verbose_name='Статус выполнения')),
                ('output', models.TextField(blank=True, default='', verbose_name='Вывод выполнения (stdout + stderr)')),
                ('ai_feedback', models.TextField(blank=True, default='', verbose_name='Фидбек от AI')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Оценка AI')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to='courses.assignment', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='code_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Попытка кода',
                'verbose_name_plural': 'Попытки кода',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
