# Generated by Django 5.0.1 on 2026-04-27 11:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignments', '0002_add_code_submission'),
        ('courses', '0007_add_assignment_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EssaySubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_content', models.TextField(verbose_name='Текст ответа')),
                ('ai_feedback', models.TextField(blank=True, null=True, verbose_name='Фидбек от AI')),
                ('score', models.IntegerField(blank=True, null=True, verbose_name='Оценка AI')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_submissions', to='courses.assignment', verbose_name='Задание')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='essay_submissions', to=settings.AUTH_USER_MODEL, verbose_name='Студент')),
            ],
            options={
                'verbose_name': 'Попытка эссе',
                'verbose_name_plural': 'Попытки эссе',
                'ordering': ['-created_at'],
            },
        ),
    ]
