# Generated by Django 5.0.1 on 2026-01-05 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLessonProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_competed', models.BooleanField(default=False, verbose_name='Пройден')),
                ('completed_at', models.DateTimeField(auto_now=True, verbose_name='Дата выполнения')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_progress', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progres', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Прогресс по уроку',
                'verbose_name_plural': 'Прогресс обучения',
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
