# Generated by Django 5.0.1 on 2026-01-05 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userlessonprogress',
            old_name='is_competed',
            new_name='is_completed',
        ),
    ]
