# Generated by Django 5.0.1 on 2026-03-25 11:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_rename_is_competed_userlessonprogress_is_completed'),
        ('courses', '0002_db_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userlessonprogress',
            index=models.Index(fields=['user', 'lesson'], name='progress_user_lesson_idx'),
        ),
    ]
