# Generated by Django 5.0.1 on 2026-03-25 13:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0003_db_indexes'),
        ('courses', '0003_add_lesson_pdf_file'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userlessonprogress',
            name='attempt_count',
            field=models.PositiveIntegerField(default=1, verbose_name='Число попыток'),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='quiz_score',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Результат теста (0–1)'),
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='time_spent_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Время на уроке (сек)'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='completed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата последнего действия'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)], verbose_name='Балл за попытку (0–1)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to='courses.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Попытка теста',
                'verbose_name_plural': 'Попытки тестов',
                'ordering': ['created_at'],
            },
        ),
    ]
