# Generated by Django 5.0.1 on 2026-04-19 18:06

import courses.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_enrollment_model'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CourseDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=courses.models._document_upload_path, verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('extracted_text', models.TextField(blank=True, default='', verbose_name='Извлечённый текст')),
                ('status', models.CharField(choices=[('pending', 'Ожидает парсинга'), ('parsed', 'Текст извлечён'), ('error', 'Ошибка парсинга')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, default='', verbose_name='Сообщение об ошибке')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='courses.course', verbose_name='Курс')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL, verbose_name='Загружено преподавателем')),
            ],
            options={
                'verbose_name': 'Документ курса',
                'verbose_name_plural': 'Документы курса',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
