# Generated by Django 5.0.1 on 2026-04-19 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_coursedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursedocument',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает парсинга'), ('parsed', 'Текст извлечён'), ('indexed', 'Проиндексировано в RAG'), ('error', 'Ошибка')], db_index=True, default='pending', max_length=10, verbose_name='Статус'),
        ),
    ]
