# Generated by Django 5.0.1 on 2026-04-26 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_add_indexed_status_to_coursedocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название задания')),
                ('description', models.TextField(verbose_name='Условие задания')),
                ('assignment_type', models.CharField(choices=[('essay', 'Эссе'), ('code', 'Код'), ('ai_dialog', 'ИИ-диалог'), ('quiz', 'Тест'), ('file_upload', 'Загрузка файла')], db_index=True, default='essay', max_length=20, verbose_name='Тип задания')),
                ('content', models.JSONField(blank=True, default=dict, verbose_name='Специфичные данные задания')),
                ('max_score', models.IntegerField(default=10, verbose_name='Максимальный балл')),
                ('order', models.IntegerField(db_index=True, default=0, verbose_name='Порядок')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_assignments', to='courses.lesson', verbose_name='Урок')),
            ],
            options={
                'verbose_name': 'Задание',
                'verbose_name_plural': 'Задания',
                'ordering': ['order'],
            },
        ),
    ]
